
# Kata terlarang untuk filter judul video YouTube
FORBIDDEN_TITLE_PATTERNS: list[tuple[str, str]] = [
    (r'#shorts|\bshorts\b', 'Shorts'),
    (r'\b(press conference|presser|press|conferência|conferencia|prensa|conferenza|stampa|pressekonferenz|conférence)\b', 'Press Conference'),
    (r'\b(interviews?|entrevista|entrevistas|declarações|declaraciones|reacciones|réactions|interviste|dopogara)\b', 'Interview'),
    (r'\b(rescaldo|post-match|post match|pre-match|pre match|previa|dopopartita|debrief|aftermatch)\b', 'Post/Pre-Match Talk'),
    (r'\b(training|behind the scenes|inside matchday|inside anfield|vlog)\b', 'Training/BTS'),
    (r'\b(fan reaction|reactions?|watchalong)\b', 'Reaction'),
    (r'\b(previews?|pre-match|previa)\b', 'Preview'),
    (r'\b(wsl|women|féminine|feminina)\b', 'Women Match'),
    (r'\b(youth|youths|youth league|u15|u16|u17|u18|u19|u20|u21|u22|u23|primavera|juvenil|sub-15|sub-17|sub-19|sub-20|sub-23|cantera|akademie|junioren|juniors?)\b|\bu[- ]?(?:15|16|17|18|19|20|21|22|23)\b', 'Youth Match'),
    (r'\b(tous les buts|all goals|all highlights)\b', 'Compilation/All Goals'),
    (r'\brésumé\s+.*\bjournée\b', 'Weekly Round Review'),
]

# Pemetaan nama tim ke handle resmi YouTube
EUROPEAN_CLUB_HANDLES: dict[str, str] = {
    # England - Premier League
    "arsenal": "@arsenal",
    "aston villa": "@avfcofficial",
    "bournemouth": "@afcbournemouth",
    "brentford": "@brentfordfc",
    "brighton": "@OfficialBHAFC",
    "chelsea": "@chelseafc",
    "coventry city": "@coventrycityfc",
    "crystal palace": "@OfficialCPFC",
    "everton": "@everton",
    "fulham": "@fulhamfc",
    "hull city": "@hullcityofficial",
    "ipswich town": "@ipswichtown",
    "ipswich": "@ipswichtown",
    "leeds united": "@leedsunited",
    "liverpool": "@liverpoolfc",
    "manchester city": "@mancity",
    "manchester united": "@manutd",
    "newcastle united": "@NUFC",
    "newcastle": "@NUFC",
    "nottingham forest": "@NottinghamForestFC",
    "sunderland": "@sunderlandafc",
    "tottenham": "@tottenhamhotspur",
    "west ham": "@westham",
    "wolverhampton": "@wolves",
    "wolves": "@wolves",

    # Spain - LaLiga & UEFA
    "real madrid": "@realmadrid",
    "barcelona": "@fcbarcelona",
    "atletico madrid": "@atleticodemadrid",
    "atlético madrid": "@atleticodemadrid",
    "girona": "@GironaFC",
    "real sociedad": "@realsociedad",
    "athletic club": "@athleticclubtv",
    "athletic bilbao": "@athleticclubtv",
    "villarreal": "@villarrealcf",
    "real betis": "@realbetis",
    "sevilla": "@sevillafc",

    # Germany - Bundesliga & UEFA
    "bayern munich": "@fcbayern",
    "bayern münchen": "@fcbayern",
    "bayern": "@fcbayern",
    "borussia dortmund": "@bvb",
    "dortmund": "@bvb",
    "bayer 04 leverkusen": "@bayer04fussball",
    "leverkusen": "@bayer04fussball",
    "rb leipzig": "@rbleipzig",
    "leipzig": "@rbleipzig",
    "vfb stuttgart": "@vfb",
    "stuttgart": "@vfb",
    "eintracht frankfurt": "@eintracht",
    "frankfurt": "@eintracht",
    "hoffenheim": "@tsghoffenheim1899",

    # Italy - Serie A & UEFA
    "inter milan": "@inter",
    "internazionale": "@inter",
    "inter": "@inter",
    "juventus": "@juventus",
    "ac milan": "@acmilan",
    "milan": "@acmilan",
    "atalanta": "@atalantabc",
    "bologna": "@siamobolognatv",
    "as roma": "@officialasroma",
    "roma": "@officialasroma",
    "ss lazio": "@officialsslazio",
    "lazio": "@officialsslazio",
    "napoli": "@officialsscnapoli",
    "fiorentina": "@FiorentinaOfficial",

    # France - Ligue 1 & UEFA
    "paris saint-germain": "@psg",
    "psg": "@psg",
    "as monaco": "@asmonaco",
    "monaco": "@asmonaco",
    "lille": "@LOSC",
    "stade brestois": "@SB29",
    "brest": "@SB29",
    "olympique lyonnais": "@olympiquelyonnais",
    "lyon": "@olympiquelyonnais",
    "olympique de marseille": "@om_officiel",
    "marseille": "@om_officiel",
    "ogc nice": "@ogcnice",
    "nice": "@ogcnice",
    "rc lens": "@RCLens",
    "racing club de lens": "@RCLens",
    "lens": "@RCLens",
    "fc lorient": "@FCLorientOfficiel",
    "lorient": "@FCLorientOfficiel",

    # Other UEFA League Phase
    "sporting cp": "@sportingcp",
    "sporting": "@sportingcp",
    "sl benfica": "@slbenfica",
    "benfica": "@slbenfica",
    "fc porto": "@fcporto",
    "porto": "@fcporto",
    "sc braga": "@scbragaoficial",
    "braga": "@scbragaoficial",
    "feyenoord": "@feyenoord",
    "psv eindhoven": "@psv",
    "psv": "@psv",
    "afc ajax": "@afcajax",
    "ajax": "@afcajax",
    "celtic": "@celticfc",
    "rangers": "@rangersfc",
    "club brugge": "@ClubBruggeKV",
    "salzburg": "@fcrbs",
    "sturm graz": "@sksturmtv",
    "dinamo zagreb": "@gnkdinamo",
    "crvena zvezda": "@crvenazvezdafk",
    "red star": "@crvenazvezdafk",
    "sparta praha": "@ACSpartaPraha",
    "sparta prague": "@ACSpartaPraha",
    "slovan bratislava": "@skslovanbratislava",
    "shakhtar donetsk": "@fcshakhtar",
    "shakhtar": "@fcshakhtar",
    "young boys": "@bscyb_offiziell",
    "galatasaray": "@galatasaray",
    "fenerbahce": "@fenerbahce"
}

# Channel ID permanen statis (0 kuota)
PERMANENT_CHANNEL_IDS: dict[str, str] = {
    # England
    "@arsenal": "UCpryVRk_VDudG8SHXgWcG0w",
    "@avfcofficial": "UCICNP0mvtr0prFwGUQIABfQ",
    "@afcbournemouth": "UCeOCuVSSweaEj6oVtJZEKQw",
    "@brentfordfc": "UCAalMUm3LIf504ItA3rqfug",
    "@OfficialBHAFC": "UCf-cpC9WAdOsas19JHipukA",
    "@chelseafc": "UCU2PacFf99vhb3hNiYDmxww",
    "@coventrycityfc": "UCch_NWdo3JWKngAyO9XlycA",
    "@OfficialCPFC": "UCWB9N0012fG6bGyj486Qxmg",
    "@everton": "UCtK4QAczAN2mt2ow_jlGinQ",
    "@fulhamfc": "UC2VLfz92cTT8jHIFOecC-LA",
    "@hullcityofficial": "UC8MRV5E-Bi5qWomGjOF0ZQg",
    "@ipswichtown": "UCjNwxJec96lMWgCXjEDhXgQ",
    "@leedsunited": "UCyQcJHDN4uYfPa1DHzKVSnw",
    "@liverpoolfc": "UC9LQwHZoucFT94I2h6JOcjw",
    "@mancity": "UCkzCjdRMrW2vXLx8mvPVLdQ",
    "@manutd": "UC6yW44UGJJBvYTlfC7CRg2Q",
    "@newcastle": "UCywGl_BPp9QhD0uAcP2HsJw",
    "@newcastleunited": "UCywGl_BPp9QhD0uAcP2HsJw",
    "@NUFC": "UCywGl_BPp9QhD0uAcP2HsJw",
    "@NottinghamForestFC": "UCyAxjuAr8f_BFDGCO3Htbxw",
    "@sunderlandafc": "UCrw-7k6yJc0EMJdf-0BAkoQ",
    "@tottenhamhotspur": "UCEg25rdRZXg32iwai6N6l0w",
    "@westham": "UCTqZqExWiRRyAwsVk9Yjk0g",
    "@wolves": "UC3HQsXVXXt3cCoSL_aYiC5w",
    
    # Spain
    "@realmadrid": "UCWV3obpZVGgJ3j9FVhEjF2Q",
    "@fcbarcelona": "UC14UlmYlSNiQCBe9Eookf_A",
    "@atleticodemadrid": "UCuzKFwdh7z2GHcIOX_tXgxA",
    "@GironaFC": "UC6x5gKUZpXuKDujmaHc3Xhg",
    "@realsociedad": "UCkNMta6lLRCaOuXl3t9iG-w",
    "@athleticclubtv": "UCUiLE_NqFKarAXFhhmXiIFA",
    "@villarrealcf": "UC0MLWyQ0L7uEZY8wbkDSTkw",
    "@realbetis": "UCeB7JZwcar2fVoK2w2f9OwA",
    "@sevillafc": "UCLy9lmj_0cqffXUzbGHNmYA",
    
    # Germany
    "@fcbayern": "UCZkcxFIsqW5htimoUQKA0iA",
    "@bvb": "UCK8rTVgp3-MebXkmeJcQb1Q",
    "@bayer04fussball": "UC_DjAsoxu-gvjAahj0yiZJw",
    "@rbleipzig": "UCkZwB4IGoNBvRmVT2gaO4XA",
    "@vfb": "UCNjHTx_URHNiZvjW-uzIf4Q",
    "@eintracht": "UCDFp4bscTFm8hYxCBx-tIXg",
    "@tsghoffenheim1899": "UCYnzpk_ECf4E2QWc9DBWjBQ",
    
    # Italy
    "@inter": "UCvXzEblUa0cfny4HAJ_ZOWw",
    "@juventus": "UCLzKhsxrExAC6yAdtZ-BOWw",
    "@acmilan": "UCKcx1uK38H4AOkmfv4ywlrg",
    "@atalantabc": "UC0R-isVeRhMDe3vFTWP5Spg",
    "@siamobolognatv": "UCaUywe79ysewBvPXljIZ__w",
    "@officialasroma": "UC5jJFSjh9rq91_m71YTOafA",
    "@officialsslazio": "UCVtDCsB0UlIkDn2kjsva3WA",
    "@officialsscnapoli": "UC4OVB27DpaefFvPx2nLu4vA",
    "@FiorentinaOfficial": "UC9nwpWq73kl4e2a51d1aCog",
    "@acffiorentina": "UC9nwpWq73kl4e2a51d1aCog",
    
    # France
    "@psg": "UCt9a_qP9CqHCNwilf-iULag",
    "@asmonaco": "UCHy548EHHX9f-ETJlm18Jiw",
    "@LOSC": "UCae9u1pNGzaklyZC8OKkeCQ",
    "@SB29": "UCau2KOow38YFyBV-wFRsJQA",
    "@olympiquelyonnais": "UCzHCZXmqIdjqRnpdp0l_T6g",
    "@om_officiel": "UCoKweTwEeA-D9vuSVw_Z_DQ",
    "@om": "UCoKweTwEeA-D9vuSVw_Z_DQ",
    "@ogcnice": "UCAvm8jHWe-8K2kZK-7ynIHA",
    "@RCLens": "UCE-f1Taamum6q2S-Ve4koSw",
    "@FCLorientOfficiel": "UC1LeTxFgKYwMeQjRjLyGRTQ",
    "@fclorient": "UC1LeTxFgKYwMeQjRjLyGRTQ",
    
    # Netherlands, Portugal, Scotland & Others
    "@feyenoord": "UCg_DGzRRIQlXpHxCrMMiAIQ",
    "@psv": "UC_2ynsXrRrKP8zYrU7Hc06A",
    "@afcajax": "UCEvabswk_K5pU_Lg_j11b6Q",
    "@sportingcp": "UC8-w0D81b-5uSg6e7V9jE2w",
    "@slbenfica": "UCyZ4X7R1t-K9i6u2D6_yL8w",
    "@fcporto": "UCjPzK4Fv1gN2fG8H_u9v9sw",
    "@scbragaoficial": "UCa5R4qg2p9kX-7g_j11b6Q",
    "@celticfc": "UC8-w0D81b-5uSg6e7V9jE2w",
    "@rangersfc": "UCyZ4X7R1t-K9i6u2D6_yL8w",
    "@ClubBruggeKV": "UCjPzK4Fv1gN2fG8H_u9v9sw",
    "@fcrbs": "UCa5R4qg2p9kX-7g_j11b6Q",
    "@sksturmtv": "UC8-w0D81b-5uSg6e7V9jE2w",
    "@gnkdinamo": "UCyZ4X7R1t-K9i6u2D6_yL8w",
    "@crvenazvezdafk": "UCjPzK4Fv1gN2fG8H_u9v9sw",
    "@ACSpartaPraha": "UCa5R4qg2p9kX-7g_j11b6Q",
    "@skslovanbratislava": "UC8-w0D81b-5uSg6e7V9jE2w",
    "@fcshakhtar": "UCyZ4X7R1t-K9i6u2D6_yL8w",
    "@bscyb_offiziell": "UCjPzK4Fv1gN2fG8H_u9v9sw",
    "@galatasaray": "UCa5R4qg2p9kX-7g_j11b6Q",
    "@fenerbahce": "UC8-w0D81b-5uSg6e7V9jE2w",
}

# Custom keyword aliases untuk search query
CUSTOM_KEYWORD_ALIASES: dict[str, list[str]] = {
    "borussia dortmund": ["dortmund", "bvb"],
    "bayern münchen": ["bayern", "bayern munich"],
    "bayer 04 leverkusen": ["leverkusen", "bayer leverkusen"],
    "manchester united fc": ["man united", "man utd"],
    "manchester city fc": ["man city"],
    "tottenham hotspur fc": ["spurs", "tottenham"],
    "wolverhampton wanderers fc": ["wolves"],
    "newcastle united fc": ["newcastle"],
    "brighton & hove albion fc": ["brighton"],
    "nottingham forest fc": ["nottingham"],
    "paris saint-germain fc": ["psg"],
    "olympique de marseille": ["marseille", "om"],
    "olympique lyonnais": ["lyon", "ol"],
    "stade rennais fc 1901": ["rennes"],
    "stade brestois 29": ["brest"],
    "club atlético de madrid": ["atletico madrid"],
    "athletic club": ["athletic bilbao"],
    "fc internazionale milano": ["inter"],
    "us sassuolo calcio": ["sassuolo"],
}
